# -*- coding: utf-8 -*-
"""Статистика_такси.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYregeib_-enJzj1mcHt7uEvnb2mJyUv
"""

import numpy as np
float_formatter="{:.2f}".format
np.set_printoptions(formatter={"float_kind":float_formatter})
data=np.genfromtxt('data.csv',delimiter=',',skip_header=True)
spid_arr=data[:,7]/(data[:,8]/3600) # Массив со скоростями поездок (расстояние/время)
spid_arr.mean() # Средняя скорость такси
data[data[:,1]==2] # Выбор статистики поездок за февраль
np.shape(data[data[:,1]==2])[0] # Кол-в поездок за февраль
data[data[:,12]>50] # Выбор статистики поездок с чаевыми более 50$
np.shape(data[data[:,12]>50])[0] # Кол-в поездок с чаевыми более 50$
np.cov(data[:,[7,8,-2,-3]],rowvar=False) # Массив ковариаций - как связаны длительность по времени, по расстоянию, стоимость поездки и чаевые