# -*- coding: utf-8 -*-
"""Анализ_продаж.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2q35A-q9GFKxdxgLC3j6kcyTOTUKJKS
"""

# Самая ходовая товарная группа
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib import colors as mcolors
mcolors.CSS4_COLORS
dfp=pd.read_excel('products.xlsx')
dfo=pd.read_excel('orders.xlsx')
df=dfo.merge(dfp, left_on='product_id', right_on='product_id')
df1=df.groupby(['level1']).agg({'quantity':'sum'}).reset_index().sort_values('quantity',ascending=False)
df1.columns=['Category','Count-sum']
plt.figure(figsize=(10, 6))
max_value=df1['Count-sum'].max()
for i,v in enumerate(df1['Count-sum']): plt.text(v+max_value*0.01,i,f'{int(v):,}',ha='left',va='center',fontsize=8)
plt.barh(df1['Category'], df1['Count-sum'], color='aquamarine')
plt.gca().invert_yaxis()
plt.title('Категории товаров и проданные позиции', color='green')
plt.xlabel('Количество проданных товаров, шт.')
plt.grid(alpha=0.2);
df1

# Распределение продаж по подкатегориям
import pandas as pd
dfp=pd.read_excel('products.xlsx')
dfo=pd.read_excel('orders.xlsx')
df=dfo.merge(dfp, left_on='product_id', right_on='product_id')
df1=df.groupby(['level1','level2']).agg({'quantity':'sum'}).reset_index().sort_values(['level1','quantity'],ascending=[True, False])
df1.columns=['Category', 'Subcategory','Count-sum']
df1

# Найти средний чек на заданную дату - 13.01.2022
import pandas as pd
df=pd.read_excel('orders.xlsx')
df['accepted_at']=pd.to_datetime(df['accepted_at'],format='%Y-%m-%d %H:%M:%S').dt.date
df=df[df['accepted_at']==pd.Timestamp('2022-01-13').date()]
df['sum']=df['quantity']*df['price']
df1=df.groupby(['order_id'])['sum'].sum().reset_index()
df2=df1['sum'].mean()
print(f"Средний чек за 13.01.2022: {df2:,.2f} рублей")

# Доля промо в заданной категории
import pandas as pd
import matplotlib.pyplot as plt
dfp=pd.read_excel('products.xlsx')
dfo=pd.read_excel('orders.xlsx')
df=dfo.merge(dfp, left_on='product_id', right_on='product_id')
df['summ']=df['quantity']*df['price']
df1=df[(df['level1']=='Сыры')]
df01=df1['quantity'].sum() # Все сыры (с промо и без)
df2=df1[(df1['regular_price']!=df1['price'])]
df02=df2['quantity'].sum()  # Cыры c промо
df03=df01-df02  # Обычные сыры (без промо)
plt.figure(figsize=(8, 6))
plt.pie([df02, df03],labels=['Промо-продажи','Обычные продажи'],colors=['#FF6B6B','#4ECDC4'],
        explode=(0.1, 0),shadow=True,startangle=90,textprops={'fontsize': 12},autopct='%1.1f%%')
plt.title('Распределение продаж в категории "Сыры"',fontsize=14, color='red');
print(f"Доля промо в категории 'Сыры': {(df02/df01)*100:,.2f}%")

# Расчет маржи по категориям
import matplotlib.pyplot as plt
import pandas as pd
dfp=pd.read_excel('products.xlsx')
dfo=pd.read_excel('orders.xlsx')
df=dfo.merge(dfp, left_on='product_id', right_on='product_id')
df['marge']=df['quantity']*(df['price']-df['cost_price'])
# Расчет маржи по категориям в руб.
df1=df.groupby('level1')['marge'].agg('sum').reset_index().sort_values('marge',ascending=False)
df1.columns=['Category','Marge_rub']
# Расчет маржи по категориям в %
df2=(df.groupby('level1')['marge'].sum()/df['marge'].sum()*100).round(2).reset_index().sort_values('marge',ascending=False)
df2.columns=['Category','Marge_%']

# Барчарт 1
plt.figure(figsize=(10, 6))
max_value=df1['Marge_rub'].max()
for i,v in enumerate(df1['Marge_rub']): plt.text(v+max_value*0.01,i,f'{int(v):,} р.',ha='center',va='center',
                                                 fontsize=8)
plt.barh(df1['Category'],df1['Marge_rub'],color='skyblue')
plt.gca().invert_yaxis()
plt.title('Распределение маржи в руб. по категориям', color='blue')
plt.xlabel('Маржа в руб.')
plt.grid(alpha=0.2)

# Барчарт 2
plt.figure(figsize=(10, 6))
max_value=df2['Marge_%'].max()
for i,v in enumerate(df2['Marge_%']): plt.text(v+max_value*0.01,i,f'{v:.2f}%',ha='center',va='center',
                                                 fontsize=8)
plt.barh(df2['Category'],df2['Marge_%'],color='yellow')
plt.gca().invert_yaxis()
plt.title('Распределение маржи в % по категориям', color='green')
plt.xlabel('Маржа в %')
plt.grid(alpha=0.2)

# ABC анализ
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
dfp=pd.read_excel('products.xlsx')
dfo=pd.read_excel('orders.xlsx')
# ABC-анализ продаж по количеству
df=dfo.merge(dfp, left_on='product_id', right_on='product_id')
df1=df.groupby('level2')['quantity'].sum().reset_index().sort_values('quantity',ascending=False)
df1.columns=['Subcategoty','Sum_quantity']
df1['Cumulative_%_quantity']=(df1['Sum_quantity'].cumsum()/(df1['Sum_quantity'].sum())*100).round(2)
df1['ABC-quantity']=np.where(df1['Cumulative_%_quantity']<=80,'A',np.where(df1['Cumulative_%_quantity']<=95,'B','C'))
df1
# ABC-анализ по сумме продаж
df['summ']=df['quantity']*df['price']
df2=df.groupby('level2')['summ'].sum().reset_index().sort_values('summ',ascending=False)
df2.columns=['Subcategoty','Sum_sales']
df2['Cumulative_%_summ']=(df2['Sum_sales'].cumsum()/(df2['Sum_sales'].sum())*100).round(2)
df2['ABC-summ']=np.where(df2['Cumulative_%_summ']<=80,'A',np.where(df2['Cumulative_%_summ']<=95,'B','C'))
df2
# Итоговая группа на основании двух анализов
df3=df2.merge(df1, left_on='Subcategoty', right_on='Subcategoty')
df3['ABC-category']=df3['ABC-quantity']+df3['ABC-summ']
df3